---
- name: install maven
  hosts: all
  become: true

  tasks:
  - name: Maven
    ansible.builtin.get_url:
      url: https://dlcdn.apache.org/maven/maven-3/3.9.2/binaries/apache-maven-3>
      dest: /home/ubuntu/
      mode: 0777

