---
- name: install maven
  hosts: all
  become: true
  
  tasks: 
  - name: download maven software
    ansible.builtin.get_url:
      url: https://dlcdn.apache.org/maven/maven-3/3.8.8/binaries/apache-maven-3.8.8-bin.tar.gz
      dest: /home/ubuntu/
      mode: '0777'
